<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pits_googlecse"
 *
 * Auto generated by Extension Builder 2016-10-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Google CSE',
    'description' => 'Google custom search for your very own website.',
    'category' => 'plugin',
    'author' => 'Anu Bhuvanendran Nair',
    'author_email' => 'anu.bn@pitsolutions.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-8.3.0',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);